<?php

namespace user\controllers;

use user\models\CatalogModel;
use core\controllers\ViewsController;

class CatalogController extends CatalogModel implements ViewsController
{

    protected $view_file;

    private $model_auth;
    private $login;
    private $pass;

    public function __construct($view_file)
    {
        $this->login = htmlspecialchars($_POST['login_auth']);
        $this->pass = htmlspecialchars($_POST['pass_auth']);

        $this->view_file = $view_file;

        $this->model_auth = new CatalogModel();

    }

    public function render()
    {

        if (file_exists('./app/user/views/' . $this->view_file . '.php')) {

            require './app/user/views/' . $this->view_file . '.php';

        }
    }

    public function CatalogProd()
    {
        return parent::CatalogProd(); // TODO: Change the autogenerated stub
    }
}
